export const ROUTES = {
  ACCOUNT: {
    ROOT: "/account",
    My_DKC_BAGS: "/account/my-dkc-bags",
    My_DKC_BAG_DETAILS: (id: string) => `/account/my-dkc-bag-details/${id}`,
    ORDER_HISTORY: `/account/order-history`,
    ORDER_DETAILS: (id: string) => `/account/order-details/${id}`,
    VERIFY_BAG_RETURN: (id: string) => `/account/verify-bag-return/${id}`,
    PERSONAL_DETAILS: `/account/personal-details`,
    MY_RENTALS: `/account/my-rentals`,
    RENT_ORDER_DETAILS: (slug: string) => `/account/rent-order-details/${slug}`,
    MY_ITEMS: `/account/my-items`,
    MY_IMPACT: `/account/my-impact`,
    MY_ITEM_DETAILS: (id: string) => `/account/my-items/${id}`,
    MY_EARNINGS: `/account/my-earnings`,
    MY_COUPONS: "/account/my-coupons",
    REDEEM_COUPONS: "/account/redeem-coupons",
    DIGITAL_WARDROBE: {
      ROOT: `/account/digital-wardrobe`,
      ALL_WARDROBE_ITEMS: `/account/digital-wardrobe/all-wardrobe-items`,
      ALL_FAMILY_MEMBERS: `/account/digital-wardrobe/all-family-members`,
      WARDROBE_PRODUCT_DETAILS: (id: string) =>
        `/account/digital-wardrobe/wardrobe-product/${id}`,
      WARDROBE_RECOMMENDATION_PRODUCTS: (id: string) =>
        `/account/digital-wardrobe/wardrobe-recommendation-products/${id}`,
    },
    MY_PRE_ORDERS: {
      ROOT: `/account/my-pre-order`,
      PRE_ORDER_DETAILS: (id: string) => `/account/my-pre-order/${id}`,
    },
  },
  PRODUCTS: {
    ROOT: "/products",
    ORDER_DKC_BAG: `/products/order-dkc-bag`,
    SLUG: (slug: string) => `/products/${slug}`,
    PRODUCT_REVIEWS: (productId: string) =>
      `/products/product-reviews?productId=${productId}&pageSize=10&dbField=createdDate&isAscending=false`,
    RATE_PRODUCT: (orderId: string) =>
      `/products/rate-product?orderId=${orderId}`,
  },
  COLLECTION: {
    ROOT: "/collections",
    COLLECTION_PRODUCTS: (slug: string) => `/collections/${slug}`,
  },
  BLOGS: {
    ROOT: "/blogs",
    BLOG_DETAILS: (id: string) => `/blogs/${id}`,
  },
  BRAND: {
    ROOT: "/brand/all",
    BRAND_PRODUCTS: (slug: string) => `/products?brand=${slug}`,
  },
  PARTNER_BRAND: (slug: string) => `/partner-brand?brand=${slug}`,
  IMAGE_SEARCH: (imageUrl: string) => `/image-search?imageUrl=${imageUrl}`,
  CATEGORY: {
    ROOT: "/category/all",
    CATEGORY_PRODUCTS: (slug: string) => `/category/${slug}`,
  },
  SHOP: "/",
  WISHLIST: "/wishlist",
  PRODUCT_VALUATION: "/product-valuation",
  CART: "/cart",
  SELL: "/sell",
  TEXT_SEARCH: "/text-search",
  RENT: "/rent",
  LOGIN: "/login",
  REGISTER: "/register",
  VERIFY_SSO: "/verify-sso",
  CUSTOM_PAGES: (slug: string) => `/custom-pages/${slug}`,
  ORDER_ERROR: "/order-error",
  ORDER_SUCCESSFUL: "/order-successful",
  OTP_VERIFICATION: "/otp-verification",
  PASSWORD_CHANGE_ERROR: "/password-change-error",
  PASSWORD_CHANGE_SUCCESSFULLY: "/password-changed-successfully",
  CHECKOUT: "/checkout",
  CREATE_NEW_PASSWORD: "/create-new-password",
  FORGOT_PASSWORD: "/forgot-password",
  CONTACT_US: "/contactus",
  SHARE_WARDROBE: (id: string) => `/share-wardrobe?id=${id}`,
} as const;
